DROP TABLE IF EXISTS `student`.`companies`;
CREATE TABLE  `student`.`companies` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `batch_id` int(10) unsigned NOT NULL,
  `sub_batch_id` int(10) DEFAULT NULL,
  `user_id` int(10) DEFAULT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `company_instructions` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `company_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `parent_company` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `company_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zipcode` int(10) DEFAULT NULL,
  `country` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `international_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `switchboardnumber` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchNumber` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `addresscode` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `comapny_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `products_services` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `industry_classfication` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `employee_size` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `physician_size` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `annual_revenue` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `number_of_beds` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `foundation_year` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `company_remark` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_info1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_info2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_info3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_info4` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ForeignKeyContraints` (`batch_id`),
  CONSTRAINT `ForeignKeyContraints` FOREIGN KEY (`batch_id`) REFERENCES `batches` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;